// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvizomqkjqbseqyaeasw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2aXpvbXFranFic2VxeWFlYXN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMzU3NjAsImV4cCI6MjA2MTYxMTc2MH0.TBiKRDnOxSwak6KdCIufUyASkAmUKr-PsBwLpbCiRA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);